### ISSUE TITLE
web：用户管理增加index页面增加角色过滤器

### ISSUE THREAD

**Issue by kexiaobin11** [yunzhiclub/integration-testing#77]
![image](https://github.com/yunzhiclub/integration-testing/assets/102429209/58c9697a-d00e-4324-a5e8-1e6ac5f90928)

**Comment by wujifen** [comment]
没太懂什么意思，是角色使用拦截器吗？

**Comment by kexiaobin11** [comment]
pipe 过滤器，role_admin = 管理员 role_user = 用户
