### ISSUE TITLE
编辑用户得时候，角色没有选中

### ISSUE THREAD

**Issue by YZ-zhujie** [yunzhiclub/integration-testing#87]
![image](https://github.com/yunzhiclub/integration-testing/assets/126573058/d70636bd-25e1-461a-81ec-adc5283ee2f3)

**Comment by YZ-zhujie** [comment]
![image](https://github.com/yunzhiclub/integration-testing/assets/126573058/da360627-f1a8-4524-853c-c661a2090625)
mockapi中返回的是user，这里是role_user

**Comment by kexiaobin11** [comment]
已修正，重新测试，模拟修正为role_ 开头
